src-d/style-analyzer

lookout/core/data_requests.py

The bug in lookout was fixed. Please use new binary: https://github.com/src-d/lookout/releases/tag/v0.0.3

Enable exclude vendor

---

lookout/style/format/rules.py
lookout/style/format/tests/test_rules.py

I noticed that the apply function of sklearn was way faster than what I was using before to compute the rule to instances index I need. Here is a pull request to use it.
I also added a random forest to the tests.

Use sklearn's apply function to build instances index

---

lookout/style/format/rules.py
lookout/style/format/tests/test_format_model.py
lookout/style/format/tests/test_rules.py

Use external functions instead of `get_params` and `_get_param_names` to decide which parameters to save in the `modelforge.Model`. Fit the base model if not fitted to allow for convenient CV workflows in sklearn.

Improve sklearn compatibility

---

lookout/style/format/features.py
lookout/style/format/tests/test_features.py

Removed location features for the nodes to the right of the current node to prevent the problem from being trivial. Also refactored parent features to use the lowest common ancestor.

Remove features that make the problem trivial, refactor parents

---

lookout/style/format/analyzer.py
lookout/style/format/rules.py
lookout/style/format/tests/test_integration.py
lookout/style/format/tests/test_model.py
lookout/style/format/tests/test_rules.py
requirements.txt

The train method uses model selection to obtain the best possible set
of rules with a non destructive pruning method. We can then implement
destructive pruning if we need to further reduce the number of rules.

Implement the training of FormatAnalyzer

---

lookout/style/format/features.py
lookout/style/format/langs/javascript/tokens.py
lookout/style/format/tests/test_features.py

We discussed a while ago with @vmarkovtsev that we should extend roles to include tokens that babelfish doesn't handle out of the box.

Extend roles to nodes non-handled by bblfsh

---

lookout/style/format/analyzer.py

Sometimes we were passing `[None]` to feature extracting functions which was not a legal argument.

Fix incorrect edited lines handling

---

README.md

Fix `README.md`
* name of config file should be `config.yml` instead of `lookout.yaml`

Make name of config file consistent among guides

---

lookout/core/tests/server.py
lookout/core/tests/test_data_requests.py

The two latest `lookout` submodule updates didn't bump the binary used to perform the tests. Here is the bump.

Update lookout binary from 0.1.0 to 0.1.3 to match submodule version and update related tests

---

.travis.yml

We're not ready for v2 yet so we have to switch from latest to v1.2.0.

Fix javascript driver to v1.2.0

---

lookout/style/format/tests/test_rules_integration.py

Will help to distinguish with other types of integration tests.

Rename test_integration.py to more informative name test_rules_integration.py

---

lookout/style/format/features.py
lookout/style/format/tests/test_features.py

I add `feature_layout` field to `FeatureExtractor` class. Now we have features names in the corresponding attribute. But it is still independent of feature generation function (`_inplace_write_vnode_features`). First, I was trying to them because in case you change one you should always fix the second. It is inconvenient and can lead to bugs.
However, I decided to keep it simple for now to avoid conflicts in future changes when we decide to add more complex features than one node related.

Add feature names to FeatureExtractor

---

lookout/style/format/features.py

Length feature doesn't leak information about the current node but can still help with the formatting problem.

Add length feature to left and right siblings

---

lookout/style/format/__main__.py
lookout/style/format/quality_report.py
lookout/style/format/visualization.py

* dataset level - classification report & bad files
* file level - misprediction visualization
Example of usage:
```console
egor@egor-sourced:~/workspace/style-analyzer$ python3 -m lookout.style.format eval -i '/home/egor/workspace/tmp/freeCodeCamp/**/*' -m /tmp/home/egor/workspace/tmp/freeCodeCamp/FormatAnalyzer_1.asdf -n 10
/usr/local/lib/python3.5/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
from numpy.core.umath_tests import inner1d
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 543/543 [00:09<00:00, 58.55it/s]
Number of files: 258
could not parse file …
```

Quality checking

---

lookout/core/data_requests.py
lookout/core/garbage_exclusion.py
lookout/core/langs/javascript/garbage.py
lookout/style/format/__main__.py
lookout/style/format/analyzer.py
lookout/style/format/files_filtering.py
lookout/style/format/quality_report.py
lookout/style/format/tests/test_analyzer.py
lookout/style/format/visualization.py

Uses the lookout server exclude pattern and mirrors this behavior for debugging tools in a separate function. Also filters on max line length.

Exclude garbage from lookout data requests

---

lookout/style/format/features.py
lookout/style/format/tests/test_features.py

Add OHE Roles & split internal types and keywords into 2 cols

Dense one-hot encoding of the internal types

---

lookout/style/format/features.py

because now it is invisible in comment:
```
format: replace <newline> with <space> at column 5
```
converts to 
```
format: replace with at column 5
```

replace < and > by ` and ` in comments

---

lookout/style/format/analyzer.py

Fixes an error I've gotten after #152. @zurk if you can look into adding tests for this model serialization it'd be great, somehow we didn't catch that with travis!
```
Traceback (most recent call last):
File "lookout/style/format/research/train.py", line 64, in <module>
main()
File "lookout/style/format/research/train.py", line 60, in main
train(**vars(args))
File "lookout/style/format/research/train.py", line 46, in train
model.save(output_path)
File "/home/mog/.virtualenvs/style-analyzer/lib/python3.6/site-packages/modelforge/model.py", line 274, in save
self._write_tree(tree, output)
File "/home/mog/.virtualenvs/style-analyzer/lib/python3.6/site-packages/modelforge/model.py", line 289, in _write_tree
asdf.AsdfFile(final_tree).write_to(output, all_array_compression=ARRAY_COMPRESSION) …
```

Fix asdf serialization error

---

lookout/style/format/analyzer.py

It should be an integer value, not the value from 0 to 1.
Related: https://github.com/src-d/style-analyzer/compare/master...zurk:fix/confidence?expand=1#diff-b71e0e71a29c83c6fa2ee406a76c3baeR81

Fix "failed to parse this file" message confidence

---

lookout/style/format/features.py

Before:
```
[VirtualNode("", start=(260, 9, 6), end=(260, 9, 6), node=None, path="component-passport.js"),
VirtualNode(" ", start=(260, 9, 6), end=(261, 9, 7), node=None, path="component-passport.js"),
VirtualNode("", start=(261, 9, 7), end=(261, 9, 7), node=None, path="component-passport.js"),
```
After:
```
[VirtualNode("", y=<noop>, start=(260, 9, 6), end=(260, 9, 6), node=None, path="component-passport.js"),
VirtualNode(" ", y=<space>, start=(260, 9, 6), end=(261, 9, 7), node=None, path="component-passport.js"),
VirtualNode("", y=<noop>, start=(261, 9, 7), end=(261, 9, 7), node=None, path="component-passport.js"),]
```
In case there is no y (`y is None`) repr remains the same:
```
VirtualNode("", start=(261, 9, 7), end=(261, 9, 7), node=None, path="component-passport.js"),
```
Also, I …

Add "y= " to VirtualNode.__repr__

---

lookout/style/format/features.py

They are still understandable like `left` and `right` but easy to read in rules
Signed-off-by: konstantin <kslavnov@gmail.com>

Shorten features type names

---

lookout/style/format/features.py
lookout/style/format/langs/javascript/uast_fixers.py
lookout/style/format/tests/test_features.py

Fixes https://github.com/src-d/style-analyzer/issues/180
Also, add a new test with code in the issue.
Signed-off-by: konstantin <kslavnov@gmail.com>

Fix for 'missed some imaginary tokens` for regexp

---

lookout/style/format/feature_utils.py

1st commit fixes a bug in the repr method of VirtualNode that causes TypeErrors when extracting the features
2nd commit is just to avoid confusion reading the classes and their corresponding indices

Match CLASSES order when declaring individual classes in feature_utils

---

lookout/style/format/__main__.py
lookout/style/format/quality_report.py
lookout/style/format/rule_stat.py
lookout/style/format/utils.py

Depends on https://github.com/src-d/style-analyzer/pull/193
Before:
```
Rule 0: RuleType(attrs=(RuleAttribute(feature=1, cmp=True, threshold=1.5), RuleAttribute(feature=8, cmp=True, threshold=1.0), RuleAttribute(feature=225, cmp=True, threshold=1.0), RuleAttribute(feature=269, cmp=True, threshold=118.0)), stats=RuleStats(cls=8, conf=0.9916667, support=60.0))
Rule 1: RuleType(attrs=(RuleAttribute(feature=1, cmp=True, threshold=1.5), RuleAttribute(feature=8, cmp=True, threshold=1.0), RuleAttribute(feature=225, cmp=True, threshold=1.0), RuleAttribute(feature=269, cmp=False, threshold=118.0), RuleAttribute(feature=269, cmp=True, threshold=114.5)), stats=RuleStats(cls=7, conf=0.9992, support=625.0))
```
After:
```
Rule 0: node_start_col > 1.5 & left_1_keyword_id > 1.0 & left_3_EXPRESSION > 1.0 …
```

More statistics about rules & prettify 

---

Makefile

pylint takes a long time, so I want to ctrl+C it sometimes.
Signed-off-by: Konstantin Slavnov <kslavnov@gmail.com>

Switch order for pylint and flake documentation checks.

---

lookout/style/format/analyzer.py
lookout/style/format/descriptions.py
lookout/style/format/feature_utils.py

Ability to get comments like this:
----
format: style mismatch:
```javascript
17|function getCompletedCertCount(user) {
18|  return
19|  [
```
Replace `<newline>` with `<space>` at column 9.
Confidence: 0.896
Triggered rule # 65:
```
left_2_reserved in |.|
left_1_label in |<newline>|
left_0_reserved in |;˙{˙}|
left_0_label in |<+space>˙<-space>˙<newline>|
left_2_roles in |string|
left_0_roles in |string|
```
----
This code requires more work and some refactoring. But it is hard to do in one PR at once. 
So I left todos there. It is better to start from something at least.

Pretty comment message for debugging

---

setup.py

Setup unable to find `README.md` because it runs from another directory.
See also: https://hub.docker.com/r/srcd/style-analyzer/builds/

Fix setup and Dockerfile

---

lookout/style/format/__main__.py

before:
```
➜  style-analyzer git:(fix/print_usage) python3 -m lookout.style.format               
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/k/sourced/workdir/style-analyzer/lookout/style/format/__main__.py", line 114, in <module>
sys.exit(main())
File "/home/k/sourced/workdir/style-analyzer/lookout/style/format/__main__.py", line 110, in main
return handler(**vars(args))
TypeError: print_usage() missing 1 required positional argument: '_'
```
after:
```
➜  style-analyzer git:(fix/print_usage) python3 -m lookout.style.format
usage: __main__.py [-h] [--log-level LOG_LEVEL]
{eval,vis,rule,robust-eval} ...
```

Fix print_usage

---

lookout/style/format/benchmarks/generate_smoke.py
lookout/style/format/tests/test_benchmarks.py

I find out that if `from` and `to` commits are in reverse order lookout-sdk fails to process it. So I add revert commit on top of each style commit.

Add revert commit on top of style commit in smoke dataset

---

lookout/__init__.py
lookout/core/__init__.py
lookout/style/__init__.py
setup.py

As was discussed this `__version__` related to style-analyzer part and for the lookout-core part will be another package and module( see issue https://github.com/src-d/style-analyzer/issues/266)

Move __version__ to style submodule

---

lookout/core/lib.py
lookout/core/tests/test_lib.py
lookout/style/format/analyzer.py

Imagine the situation:
We have this code in base commit:
```python
class A:
pass
class B:
pass
```
And bad-style head commit suggests us delete one newline:
```python
class A:
pass
class B:
pass
```
We see only one deletion in the diff and ignore it now (that how `find_new_lines` works). So style analyzer gives No feedback.
I suggest to include one line before deletion and one line after. 
Also I rename `find_new_lines` to `find_modified_lines` for better understanding what the function do.

Add delete line surroundings to analyze

---

.helm_staging.yml
.travis.yml
Makefile

This will replace the docker hub builds by a Travis release that will also update the deployment in lookout staging.
This still needs the Docker credentials in Travis CI (which I don't have yet) cc @rporres

Add release to Helm and Docker hub using src-d/ci

---

lookout/style/typos/research/baseline.py
lookout/style/typos/research/create_typos.py
lookout/style/typos/research/main.py
lookout/style/typos/research/pick_subset.py

The imports of the current research code in `typos` prevent basic test discovery from working (ie the one from `python setup.py test`).

Fix imports in typos research code

---

lookout/style/format/feature_extractor.py

We should also add tests for it. 
So the point is we lose some VirtualNodes for the end of a file. For example for the file
```js
import { makeToast } from '../../common/app/Toasts/redux';
export default function flashToToast(flash) {
return Object.keys(flash)
.map(key => {
const messages = flash[key];
return messages.map(message => ({
message: message.msg,
type: key,
timeout: 5000
}));
})
.reduce((toasts, messages) => toasts.concat(messages), [])
.map(makeToast)
.map(({ payload }) => payload);
}
```
we restore ( I mean by `print("".join(v.value for v in vnodes))`) only 
```js
import { makeToast } from '../../common/app/Toasts/redux';
export default function flashToToast(flash) {
return Object.keys(flash)
.map(key => {
const messages = flash[key];
return messages.map(message => ({ …
```

Fix losing the end of file

---

lookout/style/format/analyzer.py

`AttributeError` happens if you try to merge incompatible dicts like:
```python
dict1 = dict(
b=dict(c=0)
)
dict2 = dict(
b = 0
)
merge_dicts(dict1, dict2)  # raises AttributeError
```
This PR gives proper error message that helps to understand what to fix.

Add proper error report for bad configs

---

.github/dco.yml

As I get it we decide that source{d} members should always sign-off PRs.

Remove dco.yml

---

Makefile

It is possible to use both flags `-d` and `--rm` (https://github.com/moby/moby/issues/10545#issuecomment-354560625) since v1.13. Let's use it because it is so much convenient.

Add --rm flag to make bblfsh-start

---

.travis.yml
Makefile

So, what I did:
- Add one more stage called `style`: It lasts around 3 mins and saves us one Travis slot. 
- Exclude python 3.6 check because we check it inside docker, so it was a double job. +1 more Travis slot.
- Use `make check` in Travis.

Optimize Travis

---

lookout/style/format/feature_extractor.py
lookout/style/format/feature_utils.py

Example:
```python
vnode.start.line = 10
vnode.end.line = 13
file_lines = [11]
```
Checking `vnode.start.line in file_lines` is not enough in this case, so we miss this VirtualNode before.

Fix for missing multiline VirtualNodes

---

.helm_staging.yml
.travis.yml
Makefile

This deploys to GKE staging on tag. See https://travis-ci.org/src-d/style-analyzer/builds/457197144 for a run where `srcd/style-analyzer:v0.0.0-deploy-test-00` has been deployed (pypi section had been commented to avoid uploading internal tests)
Since the used branch was on the repository and has been shared by @meyskens and myself, no rebases from master have been performed. Please let me know if you prefer a single commit and I will rebase things properly.

Add CD to project

---

lookout/style/format/analyzer.py
lookout/style/format/benchmarks/evaluate_smoke.py
lookout/style/format/descriptions.py
lookout/style/format/templates/comment_default.jinja2
lookout/style/format/tests/test_comment_generation.py

Also, Rework FormatAnalyzer.analyze() function.
Closes https://github.com/src-d/style-analyzer/issues/334
Full debug comment now looks like:
-------
format: style mismatch:
```javascript
388|            // Multiple arguments are aggregated like Promise.all array elements
389|            while (i--) {
390|                    adoptValue( resolveValues[ i ], updateFunc(i), master.reject );
```
```suggestion
while ( i-- ) {
```
Insert ␣ at column 15.
Triggered rule # 1:
```
<RULE # 1 HERE>
Confidence: 1.000. Support: 100.
```
Insert ␣ at column 18.
Triggered rule # 22:
```  
<RULE # 2 HERE>
Confidence: 1.000. Support: 100.
```
-------
And without debug info: 
-------
format: style mismatch:
Insert ␣ at column 15.
Insert ␣ at column 18.
```suggestion
while ( i-- ) {
```
-------
^ this last …

Add code line suggestion feature

---

lookout/style/format/analyzer.py
lookout/style/format/rules.py
requirements.txt
setup.py

style-analyzer was incompatible with sklearn 0.20 and src-d/ml recently bumped to it. This PR fixes the main incompatibility + the main warning we got after upgrade.

Resolve the conflict between src-d/ml and src-d/style-analyzer scikit-learn versions

---

lookout/style/format/analyzer.py

There is a case exists when`line_vnodes` empty but we are trying to get `-1` element.

Fix _group_line_nodes if line_vnodes is empty

---

lookout/style/format/feature_extractor.py
lookout/style/format/quality_report_noisy.py

I found out that we forget to convert `labels_to_class_sequences` values to tuples when we load it.
@warenlg I also remove conversion to `tuple` from your code because it should be always a tuple.
I experiensed problems in CodeGenerator when I try to convert label to class sequence: 
https://github.com/src-d/style-analyzer/blob/b5335fdff360d9bcffba8b84561dee8822b707d2/lookout/style/format/code_generator.py#L204

Fix labels_to_class_sequences values type

---

lookout/style/typos/ranking.py

Now it produces hundreds lines like:
```
[1] train-error: 0.44   validation-error: 0
[2] train-error: 0.44   validation-error: 0
[3] train-error: 0.44   validation-error: 0
[3] train-error: 0.44   validation-error: 0
...
```
I disable it.

Disable too verbose output from typos tests

---

lookout/style/format/feature_extractor.py
lookout/style/format/tests/test_features.py

Second attempt to fix missing `vnode.y`
Issue description: https://github.com/src-d/style-analyzer/pull/408#issue-237166170
and related issue: https://github.com/src-d/style-analyzer/issues/406

Fix for CodeGenerator.gerenate() and FeatureExtractor._add_noops() if we remove labels with low support

---

lookout/style/typos/tests/test_corrector.py
lookout/style/typos/tests/test_generation.py

The logic in `__eq__` is still broken but the test is not flaky anymore (by broken I mean that some logic should clearly not be in this class).

Fix flaky test in typos

---

lookout/style/format/analyzer.py
lookout/style/format/optimizer.py

@vmarkovtsev some context on why I set `prune_attributes` to `False` again:
In #426, we had the code:
```python
backup_prune_attributes = lang_config["trainable_rules"]["prune_attributes"]
lang_config["trainable_rules"]["prune_attributes"] = False
try:
finally:
lang_config["trainable_rules"]["prune_attributes"] = backup_prune_attributes
lang_config["trainable_rules"].update(bscv.best_params_)
trainable_rules = TrainableRules(**lang_config["trainable_rules"],
origin_config=lang_config)
```
And the `.update(bscv.best_params_)` overrides the restoration of the original value of `prune_attributes` which means it's effectively always `False` during training.
Since I didn't use this code in this PR it was actually turned on and hanged in Travis (too long to compute). I think we should therefore …

Restrict hyper-parameter search to base model

---

lookout/style/format/analyzer.py
lookout/style/format/quality_report.py
lookout/style/format/rule_stat.py
lookout/style/format/visualizer/server.py

I'm not really familiar with all the latest developments in the report analyzers so at this point I only raised exceptions when trying to access inexistant rules. There are probably better specific tweaks that could be applied.

Save only on > 0 rules and raise exception for empty models

---

lookout/style/format/quality_report_noisy.py
lookout/style/format/templates/noisy_quality_report.md.jinja2

Fixed https://github.com/src-d/style-analyzer/issues/453
Makes the report look like this https://github.com/warenlg/style-analyzer/blob/add-reports/lookout/style/format/reports/report_noise.md

Make the rejected part of the PR curve light grey

---

lookout/style/format/analyzer.py
lookout/style/format/benchmarks/evaluate_smoke.py
lookout/style/format/benchmarks/general_report.py
lookout/style/format/tests/test_comment_generation.py
lookout/style/format/tests/test_evaluate_smoke.py
lookout/style/format/tests/test_quality_report.py

To solve the problem mentioned in https://github.com/src-d/style-analyzer/pull/478#issuecomment-447796005
TL;DR: now it is easy to process the file without comments. No need for an ad-hoc solution.

Split FixData to LineFix and FileFix

---

lookout/style/format/analyzer.py
lookout/style/format/benchmarks/quality_report_noisy.py
lookout/style/format/classes.py
lookout/style/format/feature_extractor.py
lookout/style/format/optimizer.py
lookout/style/format/postprocess.py
lookout/style/format/rule_stat.py
lookout/style/format/rules.py
lookout/style/format/tests/test_postprocess.py
lookout/style/format/visualizer/server.py

This adds UAST check to quote predictions. Goal is to be able to detect stuff like `a = "'b'"` being changed to `a = ''b''` and breaking everything.

Fix quote UAST check

---

lookout/style/format/feature_extractor.py
lookout/style/format/tests/bugs/002_bad_line_positions/__init__.py
lookout/style/format/tests/bugs/002_bad_line_positions/browser-policy-content.js
lookout/style/format/tests/bugs/002_bad_line_positions/test.py

Related to last point of https://github.com/src-d/style-analyzer/issues/511
The main problem that for some files with specific unicode symbols like `\u2028` and `\u2029` we have bad line positions.
Should be fixed in `FeatureExtractor._parse_file()`

Fix line positions bug and add test

---

lookout/style/format/virtual_node.py

If `node.value` contains special character like `\r` it breaks `repr(node)`.
I suggest using byte representation for value.
With this fix `repr(node)` gives something like:
```
VirtualNode(b')', y=None, start=(29316, 1017, 2), end=(29317, 1017, 3), node=None, path="")
VirtualNode(b'(', y=None, start=(29317, 1017, 3), end=(29318, 1017, 4), node=None, path="")
VirtualNode(b')', y=None, start=(29318, 1017, 4), end=(29319, 1017, 5), node=None, path="")
VirtualNode(b';', y=None, start=(29319, 1017, 5), end=(29320, 1017, 6), node=None, path="")
VirtualNode(b'\r\n\r\n', y=None, start=(29320, 1017, 6), end=(29324, 1019, 1), node=None, path="")
```
before:
```
VirtualNode(")", y=None, start=(29316, 1017, 2), end=(29317, 1017, 3), node=None, path="")
VirtualNode("(", y=None, start=(29317, 1017, 3), …
```

Fix repr(node)

---

lookout/style/format/feature_extractor.py
lookout/style/format/tests/test_features.py
lookout/style/format/tests/test_quality_report.py

This is the last part of `split -> splitlines` refactoring. 
This change nothing for a regular code but fixes processing for any weird Unicode newlines that is used in JS.

Replace .split("\n") with .splitlines() in_classify_vnodes()

---

lookout/style/format/cmdline_tools.py
lookout/style/format/optimizer.py
lookout/style/format/tests/test_analyzer.py

The --bblfsh should not contain default value for smoke dataset evaluation because it blocks LOOKOUT_BBLFSHD environment variable usage. 
Without this change it is harder to use from docker container.

Rename eval-smoke-dataset parser variable and fix bblfsh arg

---

lookout/style/format/benchmarks/evaluate_smoke.py
lookout/style/format/code_generator.py
lookout/style/format/descriptions.py
lookout/style/format/tests/code_generator_data.py
lookout/style/format/tests/test_code_generator.py
lookout/style/format/tests/test_evaluate_smoke.py
lookout/style/format/tests/test_utils.py
lookout/style/format/utils.py

Related to https://github.com/src-d/style-analyzer/issues/522
So we thought that this change helps us to simplify the code of `CodeGenerator` class. But as I find out it is not so easy because we still need quite a lot of logic to process indentation changes carefully. 
To simplify the code I should implement https://github.com/src-d/style-analyzer/issues/523 first. And this helps a lot to simplify `CodeGenerator`.
But this part can be merged now.

Remove global indentation from code generator

---

lookout/style/format/classes.py
lookout/style/format/code_generator.py
lookout/style/format/feature_extractor.py
lookout/style/format/tests/code_generator_data.py
lookout/style/format/tests/test_code_generator.py
lookout/style/format/tests/test_postprocess.py
lookout/style/format/tests/test_quality_report.py

PR is based on https://github.com/src-d/style-analyzer/pull/584
Closes https://github.com/src-d/style-analyzer/issues/522
Closes https://github.com/src-d/style-analyzer/issues/523
**UPD**: Closes https://github.com/src-d/style-analyzer/issues/579
The code generator is mostly rewritten and simplified. It was not possible if we keep accumulated indentation token separately, so I merge it as was mentioned in #523.
@m09 I think this change should not affect your visualizer or any other part of the code but I want additional confirmation just in case.
**UPD**: as soon as I did it (without 3rd commit), I get some undesirable effect. 
Let's considet next code:
```javascript
list = [
"a1",
"a2",
]
```
We have next vnodes there (`!` means accumulated indentation token):
```
list␣=␣[
⏎␣⁺␣⁺"a1", …
```

Join accumulated indentation token to previous one. Refactor CodeGenerator. Split quotes to separate vnode.

---

.gitignore
Makefile
lookout/style/format/benchmarks/compare_quality_reports.py
lookout/style/format/cmdline_tools.py
lookout/style/format/tests/test_compare_quality_reports.py
lookout/style/format/tests/test_main.py

I know that we are not supposed to add new features while refactoring but it is so annoying to compare reports by your eyes each time so I add this small tool for it. 
Now you can just run
```bash
make report-quality
make report-compare
```
and see the difference between numbers.
Here the example: https://github.com/src-d/style-analyzer/pull/590#issuecomment-461429161

Add quality reports comparison

---

lookout/style/format/tests/code_generator_data.py
lookout/style/format/tests/test_code_generator.py

I just tied to fix these values when we change the vnodes structure.
(vnodes structure was not changed in this commit)
Now, these numbers are `vnode.start.offset` so it is easy to find them.

Refactor CodeGenerator tests

---

lookout/style/format/feature_extractor.py
lookout/style/format/tests/bugs/004_generate_each_line/__init__.py
lookout/style/format/tests/bugs/004_generate_each_line/jquery.layout.js
lookout/style/format/tests/bugs/004_generate_each_line/test.py
setup.py

I extract an important fix from https://github.com/src-d/style-analyzer/pull/602 that can be merged now. 
**Description:**
Fix accumulated indentation position. It is ok to have `⏎⏎␣⁺␣⁺` and then accumulated indentation token `␣␣␣␣`. But if you mix tabs and spaces (you are a really bad person) you get different line beginning. For example, accumulated indentation is `␣␣␣␣` ana d new line token is `⏎⇥⁺⇥⁺`. When you join tokens you get `⏎⇥⇥␣␣␣␣` but in the code `⏎␣␣␣␣⇥⇥`. I fix it.

Fix accumulated indentation node positioning 

---

lookout/style/format/analyzer.py
lookout/style/format/classes.py
lookout/style/format/code_generator.py
lookout/style/format/feature_extractor.py
lookout/style/format/tests/bugs/004_generate_each_line/test.py

Based on PR https://github.com/src-d/style-analyzer/pull/604.
There is the last fix for `CodeGenerator` class during this refactoring stage.
I add add new test on [JS file](https://github.com/src-d/style-analyzer/compare/master...zurk:feature/code_generator_3?expand=1&title=Fix%20accumulated%20indentation%20position&body=Add%20hard%20test%20for%20CodeGenerator%0ASigned-off-by%3A%20Konstantin%20Slavnov%20%3Ckonstantin%40sourced.tech%3E#diff-331f6bd75aae1e00a76e57ac33676f0e) with terrible style: mixed tabs and spaces, trailing whitespaces.
I find out that CodeGenetaror often cannot come up with a proper line ending. 
For example, if you have a line 
```javascript
var t=0; /*
* bla
*/
```
The suggested line will be 
```javascript
var t=0;
```
because `/*` relates to vnode from the next line. …

Fix Code Generation trailing symbols loss

---

lookout/style/format/benchmarks/evaluate_smoke.py

Closes https://github.com/src-d/style-analyzer/issues/441
I look through the code when the issue was created https://github.com/src-d/style-analyzer/blob/5af6ac4b5c4df34b61c4523bf98345c59eb6ef27/lookout/style/format/benchmarks/evaluate_smoke.py and see that there were two places where I use this function. Now I see only one, so the problem is solved and I need to fix types and remove old code.

Fix evaluate_smoke.calc_metrics() parameters type

---

Makefile
lookout/style/format/benchmarks/compare_quality_reports.py
lookout/style/format/benchmarks/expected_vnodes_number.py
lookout/style/format/benchmarks/general_report.py
lookout/style/format/benchmarks/quality_report.py
lookout/style/format/cmdline_tools.py
lookout/style/format/tests/test_main.py
lookout/style/format/tests/test_quality_report.py

Closes https://github.com/src-d/style-analyzer/issues/435
Originally I was going to delete second entry point `print_reports()` but many tests use it so I decided to keep the function. It is not so important as `generate_quality_report` but can help in detailed analysis. 
I also rename `top_repos_quality.py` to `quality_report.py` because `top_repos_quality` is a confusing name and going to move code inside `benchmarks` module a little bit to make it well organized.

Move quality report entry point to lookout.style.format

---

lookout/style/typos/preprocessing.py
lookout/style/typos/tests/test_preprocessing.py

Continue with functions for preprocessing raw data.
This one filters identifiers by leaving only those, whose tokens are all in the vocabulary. This filtered data is then used for creating train and test datasets with artificially made typos.

Add filter_splits preprocesing function

---

lookout/style/typos/analyzer.py
lookout/style/typos/tests/test_corrector_utils.py
lookout/style/typos/utils.py

This function can be replaced by one call to another function, I don't think it should be kept.

Remove flatten_data function from typos utils

---

Dockerfile
lookout/style/format/benchmarks/general_report.py
lookout/style/format/benchmarks/quality_report_noisy.py
lookout/style/format/tests/bugs/001_analyze_skips_lines/test.py
lookout/style/format/utils.py
requirements.txt
setup.py

Fix https://github.com/src-d/style-analyzer/issues/502 and https://github.com/src-d/style-analyzer/issues/501 again
This PR needs https://github.com/src-d/lookout-sdk-ml/pull/64 to be merged first as well as the latest lookout-sdk-ml release

Remove prepare_files and use parse_files from lookout-sdk-ml instead

---

lookout/style/typos/datasets_preparation.py
lookout/style/typos/tests/test_datasets_preparation.py
requirements.txt
setup.py

Train fasttext from scratch on the given data.
1. **Artificial typos are added to the input data** (the model expects data with aready correct identifiers (or major part is correct)).
Training on raw dataset of identifiers is not enough - this way model puts all misspelled words close to each other, but far from their corrections or even misspellings of the same words. But when we take several examples of the same identifier as it is and with different typos in it, the model starts putting all misspellings of one word in a single cluster, which is close to the embedding of that correct word.
**Tl;dr** it's the best way I've tried so far and it's easy.
2. I use (**original implementation of FastText**)[https://github.com/facebookresearch/fastText/tree/master/python], because in comparison …

Add fasttext training function with tests

---

lookout/style/typos/corruption.py
lookout/style/typos/preparation.py
lookout/style/typos/tests/test_corruption.py
lookout/style/typos/tests/test_preparation.py

1. Replace original indices with ranges in generated datasets.
2. Make the amount of corrupted tokens fixed during artificial typos generation.

Refactor corruption and datasets preparation

---

lookout/style/typos/corrector.py
lookout/style/typos/generation.py
lookout/style/typos/tests/test_corrector.py
lookout/style/typos/tests/test_generation.py

Super small feature: expand the vocabulary in the corrector.
After adding new tokens to the vocabulary through this method, model:
- will be enabled to suggest those new tokens as corrections
- but still will probably suggest to correct them themselves (as being inside the vocabulary is not a green light for the check pass, for we don't have a perfect vocabulary and also there are typos that are correct words of the wrong meaning).
For now i believe that this *never-suggest-corrections-for-me* set must be held in analyzer (will be implementer in the upcoming PR). But we can also try different configurations in the future.

Add expand_vocabulary method to the corrector

---

lookout/style/typos/analyzer.py
lookout/style/typos/generation.py
lookout/style/typos/tests/test_analyzer.py

Right now the token is always added to the candidates during generation, but still will not be returned as a candidate, if there are too much candidates with higher probabilities. 
~~The details should be discussed, so WIP for now.~~
UPD I guess good to merge, small almost nothing-affecting changes.

Always add token itself to the candidates

---

lookout/style/format/cmdline_tools.py
lookout/style/typos/cmdline_tools.py

Use new `modelforge.slogging.add_logging_args()` parameter: `erase_args=True`

Use automatic args erase feature from modelforge logging

---

lookout/style/typos/analyzer.py
lookout/style/typos/metrics.py
lookout/style/typos/templates/comment.md.jinja2
lookout/style/typos/tests/test_analyzer.py
lookout/style/typos/utils.py

* template
* logic to generate several candidates per identifier
* logic to compute probabilities
Now it's possible to generate comments like:
<details>
Possible typos in `Token_Taken_Tuken`, suggestions:
Candidate 1 with confidence 33%
```suggestion
var Token_Tokens_Tokens;
```
Candidate 2 with confidence 33%
```suggestion
var Token_Tokens_Then;
```
Candidate 3 with confidence 32%
```suggestion
var Token_Tokens_Token;
```
Possible typos in `someWrang_Variuble_NOME`, suggestions:
Candidate 1 with confidence 33%
```suggestion
var someRange_Variable_NODE = "bla";
```
Candidate 2 with confidence 33%
```suggestion
var someWrap_Variable_NODE = "bla";
```
Candidate 3 with confidence 33%
```suggestion
var someLang_Variable_NODE = "bla";
```
Possible typos in `some_wrang_variuble_nome`, …

Add GitHub suggestion comments generation

---

lookout/style/typos/analyzer.py
lookout/style/typos/utils.py

Minor changes to simplify work with an upcoming reporter.
1. The biggest limitation I am addressing is that `TypoFix` instance should be easily converted to a JSON object. So I exclude UAST from it.
2. Use `@with_changed_uasts_and_contents(unicode=True)`
3. Convert `pred_probs[i]` to float because it has `np.float` type which fails be converted to a JSON.
4. Remove `candidates` to `token_candidates` to be more specific.

Polish IdTyposAnalyzer

---

lookout/style/format/feature_extractor.py
lookout/style/format/uast_stability_checker.py

Fix #663. As mentioned during the sync, there were two bugs in our code but also the general invariant "A parent covers its children" is not respected in the js driver (comments can be outside of their parent).

Fix parent bug

---

lookout/style/cloner.py
lookout/style/reporter.py
lookout/style/typos/benchmarks/__init__.py
lookout/style/typos/benchmarks/typo_commits_report.py

There are two main additions:
1. An abstraction layer for all Analyzer Reporters. Class that called `Reporter`
2. `TypoCommitsReporter` reported for the commit with typos dataset. 
Note, that `Reporter` takes fix information dirrectly from lookout-sdk which is more straightforward then before.

Add reporter for typos analyzer

---

lookout/style/typos/preparation.py

Just print evaluation report to stdout (otherwise there's no much sense in evaluation except for saving the metrics to the model, if you don't count logs).

Print report in train_and_evaluate()

---

.travis.yml
Dockerfile
lookout/style/reporter.py
lookout/style/typos/analyzer.py
lookout/style/typos/benchmarks/typo_commits_report.py
lookout/style/typos/templates/commits_with_typo_dataset_report.jinja2
lookout/style/typos/tests/test_typo_commits_report.py
requirements.txt
setup.py

Closes https://github.com/src-d/style-analyzer/issues/704
With these fixes I was able to achieve the next numbers:
```
|                    metric | value    |
|--------------------------:|:---------|
|       detection_precision | 0.702    |
|          detection_recall | 0.495    |
|   detection_true_positive | 361.000  |
|  detection_false_positive | 153.000  |
| detection_false_negatives | 368.000  |
|              fix_accuracy | 0.909    |
|         top3_fix_accuracy | 1.000    |
|                   support | 2776.000 |
|               review_time | 9.148    |
```
I comment on each important moment in the self-review. 
Note, that I filter the dataset where typo was actually present on the expected line.

Fix report metric calculation for typos analyzer

---

lookout/style/common.py
lookout/style/typos/benchmarks/typo_commits_report.py
lookout/style/typos/templates/commits_with_typo_dataset_report.jinja2

I run a report and get such metrics: 
```
|                    metric |      value |
|--------------------------:|-----------:|
|       detection_precision |   0.699    |
|          detection_recall |   0.498    |
|   detection_true_positive | 370        |
|  detection_false_positive | 159        |
| detection_false_negatives | 373        |
|              fix_accuracy |   0.914    |
|         top3_fix_accuracy |   1        |
|                   support |   2.65e+03 |
|               review_time |  10.1      |
```
I do not like `2.65e+03` so I should regenerate it with this changes.
Also I include zip function to jinja2 template loading because it is not the first time we need this function.
Also I fix `detection_true_positive` metric calculation. It should not depend whether fix was …

Add formatting for all metrics in typo report

---

lookout/style/typos/benchmarks/evaluate_typos.py
lookout/style/typos/templates/quality_on_identifiers.md.jinja2

Adapt identifier-level metrics for use with the dataset, which contains non-typo-ed identifiers (add detection metrics and split accuracy on total and on-typo-ed).

Expand typos quality report

---

lookout/style/format/annotations/__init__.py
lookout/style/format/annotations/annotated_data.py
lookout/style/format/annotations/annotations.py
lookout/style/format/benchmarks/expected_vnodes_number.py
lookout/style/format/feature_extractor.py
lookout/style/format/tests/bugs/002_bad_line_positions/test.py
lookout/style/format/tests/bugs/003_classify_vnodes_negative_col/test.py
lookout/style/format/tests/test_annotations.py
lookout/style/format/tests/test_expected_vnodes_number.py
lookout/style/format/tests/test_features.py
lookout/style/format/utils.py
lookout/style/format/virtual_node.py
requirements.txt
setup.py

This PR adds Annotation tool to use instead of `VirtualNode` class (issue https://github.com/src-d/style-analyzer/issues/521).
PR contains:
- [All Annotation classes ](https://github.com/src-d/style-analyzer/pull/761/files#diff-22249ade799b2492702f2bc3bdb4868a) necessary for format analyzer.
- [AnnotationManager class](https://github.com/src-d/style-analyzer/pull/761/files#diff-f77b730022c0bcd23562b98a778c4585R48) which will be a replacement for the sequence of `VirtualNode`-s
- Most of the methods in the `FeatureExtractor` rewritten using `AnnotationManager`.
- Functions for backward compatibility. They are used to transform  `AnnotationManager` back to vnode sequence. They are going to be deleted after we finish refactoring. 
I also run a regression test to see if there any difference …

Add annotations to FeatureExtractor

---

lookout/style/typos/config.py

Loaded new dataset (1 million identifiers, as before), changes:
1. Updated splits from the TokenParser.
2. Merged rows with equal splits.

Change default identifiers dataset google drive id

---

lookout/style/typos/config.py

1. Change in the model parameters.
2. No corruption of training data. Corruption sometimes improves the quality, but not dramatically. Without it the model size is much lower.

Change fasttext training config

---

requirements.txt
setup.py

This PR fixes failing tests (see https://travis-ci.com/src-d/style-analyzer/builds/114073628)
I found out that by compare Travis logs from the last succeeded build and the failed one. I am not sure what exactly was broken in the new release (https://github.com/protocolbuffers/protobuf/releases/tag/v3.8.0) but it was.

Fix protobuf version

---

lookout/style/typos/metrics.py
lookout/style/typos/templates/scores.md.jinja2
lookout/style/typos/tests/test_metrics.py

Measure correction quality on typo-ed tokens, not on the ones, that were corrected by the model. 
That's what we do in final reports and agreed upon several times.

Replace "on_corrected" with "on_typoed" in typos metrics

---

lookout/style/typos/config.py

Load the dataset of identifiers which were split with the **biLSTM splitter** (1 million of the most frequent ones)

Change default dataset for training to the one with nn splits

---

lookout/style/typos/config.py
lookout/style/typos/preparation.py

- Use real identifier frequencies for sampling - more fair distribution
- Use 2-tokens identifiers too, before it started only with 3

Small change in fasttext training data generation
