- lookout/core/analyzer.py
- lookout/core/manager.py
- lookout/core/model_repository.py
- lookout/core/sqla_model_repository.py
> Work on model repositories and managers

- lookout/core/analyzer.py
- lookout/core/analyzer_model.py
- lookout/core/cmdline.py
- lookout/core/data_requests.py
- lookout/core/event_listener.py
- lookout/core/manager.py
- lookout/core/model_repository.py
- lookout/core/sqla_model_repository.py
> Add some docstrings

- lookout/style/format/format_analyzer.py
- lookout/style/format/research/common.py
- lookout/style/format/research/js_pipeline_intendation.ipynb
- lookout/style/format/reserved/__init__.py
- lookout/style/format/reserved/javascript.py
Partially port it to the main tree
> Refactor the format model training

- lookout/style/format/langs/javascript/tokens.py
- lookout/style/format/research/common.py
* add keywords (after exp with https://github.com/facebook/react)
* add sibling extraction - much more features & approximately the same quality
> Update feature extraction pipeline:

- lookout/style/format/rules.py
- lookout/style/format/tests/test_rules.py
Greedy method for tree pruning that minimizes the number of comparisons to do at the cost of some more memory usage.
At this point there is some code duplication (_build_instances_index) because we are all working on the same functions and I didn't want to enter some merge hell. I'll PR a refactoring later on when more stable :)
> greedy tree pruning

- lookout/style/format/rules.py
Bugfix: the greedy budget argument lagged behind and didn't use the new type.
> Fix default greedy budget and add some types in init

- lookout/style/format/rules.py
We were using the index of the classes instead of the classes themselves to make predictions up until now. 
> Fix wrong classes prediction

- lookout/style/format/features.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_integration.py
The parent detection is at the moment very strict. It will be important to test different methods (such as lowest common ancestor or some other method).
> Implement extract_features

- lookout/core/sqla_model_repository.py
- requirements.txt
- setup.py
> Create the database if it does not exist

- lookout/style/format/langs/__main__.py
- lookout/style/format/langs/javascript/tokens.py
- lookout/style/format/langs/tokens.py.jinja2
> Refactor the tokens.py

- lookout/style/format/features.py
Some files are not successfully parsed with our current method. At this point we could either use them in an unstable state (features might not make sense) or discard them. This PR goes for the second option.
> Filter out buggy files during feature extraction

- lookout/style/format/features.py
- lookout/style/format/tests/test_features.py
Some fixes for the feature extraction pipeline. Now reaches almost 100% accuracy on FreeCodeCamp.
> Fix feature extraction

- lookout/style/format/rules.py
- lookout/style/format/tests/test_format_model.py
- lookout/style/format/tests/test_integration.py
- lookout/style/format/tests/test_rules.py
Now we have:
1. Rules class to apply the rules
2. TrainableRules which trains an instance of Rules
Nothing can be None inside rules.
> Refactor Rules

- lookout/style/format/rules.py
- lookout/style/format/tests/test_rules.py
Move pruning method from the research part to the main code base.
> Add reduced_error_prune method

- lookout/core/analyzer.py
- lookout/core/cmdline.py
- lookout/core/data_requests.py
- lookout/core/manager.py
- lookout/core/modelforgecfg.py
- lookout/core/tests/test_data_requests.py
- lookout/core/tests/test_manager.py
> Add the missing modelforgecfg.py

- lookout/core/cmdline.py
- lookout/core/data_requests.py
- lookout/core/sqla_model_repository.py
> Improve the CLI experience

- lookout/core/analyzer.py
- lookout/core/data_requests.py
- lookout/core/doc/getting_started.md
- lookout/core/manager.py
- lookout/core/tests/test_data_requests.py
- lookout/core/tests/test_manager.py
- lookout/style/format/analyzer.py
Relates to src-d/issues-infrastructure#213
> ReferencePointer

- lookout/style/format/features.py
- lookout/style/format/tests/test_features.py
This is a dependency of applying the rules.
> Add filtering by line number

- lookout/style/format/analyzer.py
- lookout/style/format/features.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_integration.py
> Return vnodes from extract_features()

- lookout/style/format/features.py
- lookout/style/format/tests/test_features.py
> Add no-op nodes to be able to predict from and to lack of whitespace

- logging.yaml
- lookout/core/cmdline.py
- lookout/core/slogging.py
- lookout/core/tests/test_slogging.py
Make fine-grained logging output tweaks easy by providing a way to set levels through conf files.
> Provide a config file option to tweak loggers output levels.

- requirements.txt
- setup.py
Should be merged after https://github.com/src-d/ml/pull/310
> Update sourced.ml requirement

- lookout/style/format/analyzer.py
- lookout/style/format/features.py
- lookout/style/format/tests/test_analyzer.py
Some more logging statements to monitor analyzers training and prediction.
> Improve logging

- lookout/style/typos/typos_correction/symspell.py
Signed-off-by: Irina Khismatullina <irenekhismatullina@gmail.com>
> Add pysymspell submodule from #106 (1/6)

- lookout/style/format/features.py
- lookout/style/format/tests/test_features.py
The skipping part is implemented in this PR but it uncovered some other bug that I'll investigate later. I'll ping when it's fixed. Update: other bugs fixed in #110.
> Skip noop features

- .travis.yml
> Fix failed tests in travis

- lookout/style/format/features.py
- lookout/style/format/tests/test_features.py
It should help to debug and visualize predictions.
> Add path to VirtualNode 

- lookout/core/analyzer.py
- lookout/core/manager.py
- lookout/core/tests/test_manager.py
- lookout/style/format/analyzer.py
- lookout/style/format/features.py
Uses a dict in both analyze and train.
> Streamline config in analyzers

- lookout/core/analyzer.py
- lookout/core/doc/getting_started.md
- lookout/core/manager.py
- lookout/core/tests/test_manager.py
- lookout/style/format/analyzer.py
Edit of the core package to also keep track of the module name to be able to request the correct config.
> Fix config finding

- lookout/style/format/features.py
- lookout/style/format/langs/javascript/token_unwrappers.py
Fix the 2 last spots I found of buggy node creation. One of them I fixed with ad-hoc hack since I found no general solution that handles all cases.
> Fix empty node creation

- lookout/style/format/analyzer.py
- lookout/style/format/features.py
Small PR to allow for debugging of features.py. It's what I've been using to browse the different errors we get during parsing.
> Add debugging capabilities to features.py

- .travis.yml
> Attempt to fix the cache permissions error in CI

- lookout/style/format/analyzer.py
Hardcoded arguments -> confige arguments.
> Fix arguments - now they are from config

- lookout/core/slogging.py
- lookout/style/format/analyzer.py
Related: https://github.com/joblib/joblib/issues/180#issuecomment-149249514
> Fix the critical flaw in joblib

- .travis.yml
- lookout/style/format/features.py
- lookout/style/format/tests/test_features.py
> Fix Travis

- .travis.yml
- lookout/style/format/langs/__main__.py
> Repair the tqdm progress

- lookout/style/format/features.py
> Fix logic - now list is modified

- lookout/style/format/quality_report.py
- lookout/style/format/visualization.py
* training parameters
* a number of rules & avg. len
* load model before features to make it fail fast in case of problems with a model
> Add information about model

- lookout/core/sqla_model_repository.py
Fixes https://github.com/src-d/style-analyzer/issues/157
> Fix "relation "models" does not exist"

- lookout/style/format/__main__.py
> Fix arguments to eval & vis

- setup.py
> Downgrade sklearn to remove incompatibility with skopt

- lookout/style/format/analyzer.py
> Add more precision to score display

- lookout/style/format/analyzer.py
- lookout/style/format/features.py
- lookout/style/format/quality_report.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_rules_integration.py
- lookout/style/format/visualization.py
* Fix review for broken files
* comment for unparsable files
* config for `n_jobs` - could be useful for big repos to avoid OOM errors
> Fix review & config

- lookout/style/format/__main__.py
- lookout/style/format/analyzer.py
- lookout/style/format/quality_report.py
- lookout/style/format/rule_stat.py
- lookout/style/format/visualization.py
Depends on https://github.com/src-d/style-analyzer/pull/165.
* evaluation of rules on dataset - statistics & quality metrics
* add triggered rule to file visualization
* fix config
<details>
```
Model parameters: {'feature_extractor': {'parents_depth': 2, 'siblings_window': 5, 'debug_parsing': False}, 'lower_bound_instances': 500, 'line_length_limit': 500, 'n_iter': 5, 'trainable_rules': {'base_model_name': 'sklearn.tree.DecisionTreeClassifier', 'min_samples_leaf': 19, 'max_depth': 10, 'uncertain_attributes': True, 'top_down_greedy_budget': [False, 0.5], 'n_estimators': 10, 'prune_dataset_ratio': 0.2, 'prune_branches_algorithms': ['reduced-error'], 'prune_attributes': False, 'random_state': 42, 'min_samples_split': 18}, 'n_jobs': -1}
Stats about rules: 47 rules, avg.len. 6.1
Rule 0: …
```
> Rules quality report

- lookout/style/format/analyzer.py
- lookout/style/format/features.py
- lookout/style/format/model.py
- lookout/style/format/quality_report.py
- lookout/style/format/rule_stat.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/visualization.py
This touches quite some classes since we didn't include feature extraction as an integral part of the model yet.
> Add feature selection

- lookout/style/format/analyzer.py
- lookout/style/format/features.py
- lookout/style/format/rules.py
Format:
```
DEBUG:FormatAnalyzer:Feature importances from sklearn.ensemble.RandomForestClassifier:
left_1_y_is_<space>           : 1.59749E-01
left_1_reserved_is_throw      : 6.28934E-02
left_1_reserved_is_new        : 6.16138E-02
left_2_y_is_<+space>          : 6.01231E-02
left_1_reserved_is_super      : 5.04645E-02
left_1_y_is_<+space>          : 3.85661E-02
left_1_reserved_is_string     : 3.77613E-02
left_1_reserved_is_%=         : 3.71012E-02
left_1_reserved_is_]          : 2.79625E-02
left_1_role_is_expression     : 2.62532E-02
...
```
Signed-off-by: konstantin <kslavnov@gmail.com>
> Add debug log output of base_model_name feaure importance

- lookout/core/cmdline.py
- lookout/style/format/__init__.py
> Make analyzer tool delegate entry point to analyzers

- lookout/style/format/analyzer.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/feature_utils.py
- lookout/style/format/features.py
- lookout/style/format/quality_report.py
- lookout/style/format/rule_stat.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_rules_integration.py
- lookout/style/format/visualization.py
Also fixes the main leak wich was that we were leaking length of the current node in col_diff features.
> Refactor feature configuration and extraction

- lookout/style/format/research/seq_matching_vis.py
Sequence matching research - script for visualization.
Depends on https://github.com/src-d/style-analyzer/pull/165
> Sequence matching research

- lookout/style/format/rule_stat.py
- lookout/style/format/visualization.py
Signed-off-by: m09 <hugo@mougard.fr>
> Fix call to feature extractor in viz tools

- .flake8
- .travis.yml
- lookout/style/format/analyzer.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/langs/__main__.py
- lookout/style/format/rules.py
- lookout/style/format/tests/test_analyzer.py
We can disable some of the checks if they somehow trigger too many false positives but it should be ok as is: https://github.com/PyCQA/flake8-bugbear
> Add bugbear to CI

- lookout/style/format/__main__.py
- lookout/style/format/analyzer.py
- lookout/style/format/descriptions.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/feature_utils.py
- lookout/style/format/features.py
- lookout/style/format/quality_report.py
- lookout/style/format/rule_stat.py
- lookout/style/format/rules.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/visualization.py
This is related to #199 and #194 (due to all of us having to produce names for demos and not having time to merge).
We should probably have a quick meeting to decide what to do with those 3 PRs.
> Revamp feature names handling and related feature extraction mechanisms

- .flake8-code
- .flake8-doc
- .travis.yml
> Add doc checks to CI

- lookout/style/format/descriptions.py
Use 3 digits for confidence.
Signed-off-by:  Konstantin Slavnov <kslavnov@gmail.com>
> Print confidence and support on new line

- lookout/style/format/analyzer.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_rules_integration.py
- lookout/style/format/tests/test_utils.py
- lookout/style/format/utils.py
In the trail of @vmarkovtsev review: https://github.com/src-d/style-analyzer/pull/190#discussion_r221968467
> Add merge_dict function

- lookout/__init__.py
- setup.py
- Add `README.md` as `long_description` to `setup()`
- Include typing package requirement as `"typing;python_version<'3.5'",`.
- Remove pandas from `tests_require`, we have it in `install_requires`.
- Fix `install_requires` formatting.
- Bump minor version.
> Add long description to setup()

- lookout/style/format/visualizer/README.md
- lookout/style/format/visualizer/package-lock.json
- lookout/style/format/visualizer/package.json
Update README.md & add `serve` dependency and script.
> Minor updates to make it easier to launch vis tool

- lookout/style/format/tests/test_analyzer_integration.py
- lookout/style/format/tests/test_quality_report.py
- lookout/style/format/tests/test_rule_stat.py
- lookout/style/format/tests/test_visualization.py
Tests for quality_report:
* wrong path to model
* empty input
* normal run
* reuse trained rules to avoid multiple trainings
> Make tests great again

- lookout/style/typos/research/__main__.py
- lookout/style/typos/research/nn_prediction.py
Module with functions for creating, training and running nn model for correction embedding prediction. Model architecture is primitive for now. It can be changed in future.
In a few words model does this: it receives embedding of typo and predicts embedding of correction.
Open to suggestions for improvements. Ready to merge if everything's fine.
**UPD**
Module was moved to research folder due to its revealed useless in current project.
> Add NN prediction module from #106 (3/6)

- lookout/core/slogging.py
Handle dictionary-like & sequence-like arguments.
> Fix for logging

- lookout/style/format/tests/test_analyzer.py
- lookout/style/format/tests/test_model.py
Fixes https://github.com/src-d/style-analyzer/issues/172
> Add check for analyzer model save after training

- .dockerignore
- Dockerfile
- Makefile
> Fix Dockerfile

- lookout/style/format/feature_extractor.py
This one slipped through in #204. Should fix problems for 3.5. Fixes #226.
> Fix order of iteration

- README.md
> Add bblfsh info and javascript driver version to the main README

- lookout/style/format/__main__.py
> Factorize the addition of arguments in get_parser

- lookout/style/format/tests/test_main.py
> Add tests on handlers of the main

- lookout/style/format/visualizer/README.md
- lookout/style/format/visualizer/package.json
> Improve the visualizer README

- lookout/core/analyzer.py
- lookout/core/manager.py
- lookout/core/tests/test_manager.py
> Add DummyAnalyzerModel

- lookout/style/format/visualizer/Dockerfile.bblfsh
- lookout/style/format/visualizer/Dockerfile.client
- lookout/style/format/visualizer/Dockerfile.server
- lookout/style/format/visualizer/docker-compose.yml
- lookout/style/format/visualizer/package-lock.json
- lookout/style/format/visualizer/visualizer.yml
I only put a development docker-compose atm. It should be nice to also have a production docker-compose (probably using docker-compose.override.yml).
> Add docker setup for the visualizer

- requirements.txt
I introduce this error yesterday :man_facepalming: 
@m09 please review it because Vadim has a coding day today.
> Remove redundant and bad bblfsh version

- lookout/style/format/features.py
Fixed https://github.com/src-d/style-analyzer/issues/271
> Modify diff_col feature to get the diff from sibling-start to node-start

- lookout/core/tests/server.py
the same as https://github.com/src-d/style-analyzer/pull/260 but I leave the file in tests because it is not production-ready code.
> Minor server.py improvements

- lookout/style/format/feature_extractor.py
> Harmonize identation increase and identation decrease

- .travis.yml
Fixes #254. Follow-up to #274 since travis didn't want to trigger a build for some reason.
> Build visualizer in travis

- .gitignore
- lookout/style/format/__main__.py
- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/feature_utils.py
- lookout/style/format/tests/test_main.py
Work in progress!
This PR depends on a bunch of previous ones.
For now, there is only approximate architecture. All code needs to be polished.
> Add smoke-dataset evaluation part

- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/descriptions.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/feature_utils.py
- lookout/style/format/features.py
- lookout/style/format/langs/javascript/postprocessor.py
- lookout/style/format/quality_report.py
- lookout/style/format/research/seq_matching_vis.py
- lookout/style/format/robustness.py
- lookout/style/format/rule_stat.py
- lookout/style/format/rules.py
- lookout/style/format/tests/test_descriptions.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_robustness.py
- lookout/style/format/visualization.py
- lookout/style/format/visualizer/server.py
- lookout/style/format/visualizer/src/App.js
- lookout/style/format/visualizer/src/Visualization.js
- lookout/style/format/visualizer/src/css/Token.css
> Transform labels into sequences

- lookout/style/format/descriptions.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/tests/test_descriptions.py
> Improve rule descriptions

- lookout/style/format/feature_extractor.py
one more `List[VirtualNode]` was missing
> Fix extract_features return type

- lookout/style/format/tests/test_features.py
> Add exact match of vnodes value to complete extract_feature function

- .travis.yml
- Dockerfile
- lookout/style/format/robustness.py
- lookout/style/format/tests/test_robustness.py
- requirements.txt
- setup.py
Closes https://github.com/src-d/style-analyzer/issues/269. Partially solves https://github.com/src-d/style-analyzer/issues/291.
The new test takes 11 mins in Travis, so I think it is fine to add it.
I comment all unobvious code changes.
> Fix docker image

- lookout/style/format/descriptions.py
- lookout/style/format/feature_utils.py
And move `CLASS_REPRESENTATIONS` to feature_utils
This way it is shorter and more clear for new joined `vnode.y`.
> Improve VirtualNode.__repr__()

- lookout/style/format/feature_extractor.py
Fixed https://github.com/src-d/style-analyzer/issues/308
> Fix vnodes concatenation when analyzing several files

- lookout/style/format/visualizer/package-lock.json
- lookout/style/format/visualizer/package.json
- lookout/style/format/visualizer/src/App.tsx
- lookout/style/format/visualizer/src/ContextToken.tsx
- lookout/style/format/visualizer/src/Details.tsx
- lookout/style/format/visualizer/src/EmptyDetails.tsx
- lookout/style/format/visualizer/src/Input.tsx
- lookout/style/format/visualizer/src/SampleToken.tsx
- lookout/style/format/visualizer/src/Visualization.tsx
- lookout/style/format/visualizer/src/Wait.tsx
I also re-ran prettier, which is why the modif list is long even though the semantic changes are very small.
> Update deps and adapt code to prevent the new type error

- lookout/style/format/code_generator.py
Helps to catch strange behavior
> Improve CodeGenerator logging

- lookout/style/__init__.py
- lookout/style/typos/generation.py
- requirements.txt
- setup.py
> Bump the version and remove tqdm req

- lookout/style/format/analyzer.py
- lookout/style/format/utils.py
> Do not crash on unsupported languages

- lookout/style/format/__main__.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/code_generator.py
A lot of changes:
1. Use CogeGenerator class from https://github.com/src-d/style-analyzer/pull/297
2. New good quality measures:
3. Save not only report but files for post-analysis. 
4. Database and trained models reuse
5. Pandas great report summary (`DataFrame.describe()`) is used.
I also have a bunch of useful functions like `align()` and `align3`. Should I move it to `utils.py`?
> Update evaluate smoke dataset

- README.md
- lookout/style/typos/tests/test_corrector.py
> Fix the meaning of the unit test

- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/classes.py
- lookout/style/format/code_generator.py
- lookout/style/format/descriptions.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/features.py
- lookout/style/format/langs/javascript/postprocessor.py
- lookout/style/format/postprocess.py
- lookout/style/format/quality_report.py
- lookout/style/format/research/seq_matching_vis.py
- lookout/style/format/robustness.py
- lookout/style/format/rule_stat.py
- lookout/style/format/rules.py
- lookout/style/format/tests/code_generator_data.py
- lookout/style/format/tests/test_analyzer.py
- lookout/style/format/tests/test_descriptions.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/virtual_node.py
- lookout/style/format/visualizer/server.py
> Filter labels by support and train precision

- lookout/style/format/__main__.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/code_generator.py
- lookout/style/format/tests/test_code_generator.py
- lookout/style/format/tests/test_utils.py
- lookout/style/format/utils.py
- lookout/style/format/virtual_node.py
- Ability to generate from unpredicted vnodes
- Random code improvements
> Refactor code generation

- lookout/style/format/analyzer.py
- lookout/style/format/postprocess.py
- lookout/style/format/quality_report.py
- lookout/style/format/robustness.py
- lookout/style/format/rule_stat.py
- lookout/style/format/visualizer/server.py
Fixed https://github.com/src-d/style-analyzer/issues/338 https://github.com/src-d/style-analyzer/issues/328
> Fix the snippet generation when doing the UAST check

- setup.py
> Add all_cpu and all_gpu extras

- lookout/style/format/benchmarks/evaluate_smoke.py
Apply feedback after ML sync.
Change variable names, improve descriptions.
> Polish smoke dataset evaluation

- requirements.txt
- setup.py
> Bump lookout-sdk-ml dep to 0.1.3

- .travis.yml
- Makefile
- lookout/style/format/analyzer.py
- lookout/style/format/postprocess.py
- lookout/style/format/robustness.py
- lookout/style/format/rules.py
- lookout/style/format/tests/test_analyzer.py
- lookout/style/typos/analyzer.py
- requirements.txt
- setup.py
As discussed with @zurk, I am relaxing the label precision cutoff to 0.85
> Optimize thresholds

- lookout/style/format/virtual_node.py
> Replace tab with \t symbols in VirtualNode.__repr__

- lookout/style/format/analyzer.py
- lookout/style/format/quality_report.py
> Fix a bug in quality_report and remove BblfshClient initialization from the analyzer

- .travis.yml
- Makefile
Closes https://github.com/src-d/style-analyzer/issues/360. It was a bug introduced in https://github.com/src-d/style-analyzer/pull/327
> Fix Travis for python3.6 running inside Docker

- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/descriptions.py
- lookout/style/format/templates/comment_default.jinja2
- lookout/style/format/tests/test_comment_generation.py
- lookout/style/format/tests/test_evaluate_smoke.py
- requirements.txt
- setup.py
Use analyze_unrendered in  smoke dataset evaluation.
As was discussed we somehow should separate logic from comment creation.
> Extract analyze_unrendered from analyze

- lookout/style/format/analyzer.py
- lookout/style/format/rules.py
- lookout/style/format/tests/test_analyzer.py
Fixed https://github.com/src-d/style-analyzer/issues/367
> Remove label filtering by precision

- lookout/style/format/postprocess.py
- lookout/style/format/quality_report_noisy.py
Fixed https://github.com/src-d/style-analyzer/issues/364 and the number of filtered rules in the report
> Fix ValueError for non UTF-8 chars and fix the number of filtered rules in the report

- lookout/style/format/analyzer.py
- lookout/style/format/quality_report.py
- lookout/style/format/quality_report_noisy.py
- lookout/style/format/research/seq_matching_vis.py
- lookout/style/format/rule_stat.py
- lookout/style/format/rules.py
- lookout/style/format/visualizer/server.py
Fixes https://github.com/src-d/style-analyzer/issues/375
Also, fix Rule filtering. It was not applied. 
Fix strange behavior when analyzer tries to replace everything with `␣'`
Improve code a little bit.
> Fix artificial rules leak

- lookout/style/format/postprocess.py
Fixed https://github.com/src-d/style-analyzer/issues/377
> Fix postprocess filtering for predictions from NOOPs

- lookout/style/format/virtual_node.py
> Fix from_node failing when bblfsh.Position lacks an offset

- lookout/style/format/postprocess.py
Fixes https://github.com/src-d/style-analyzer/issues/364
Attempt 2.
> Fix UTF error during postprocessing

- lookout/style/format/analyzer.py
Fixes https://github.com/src-d/style-analyzer/issues/388
> Fix comment confidence calculation

- lookout/style/format/analyzer.py
- lookout/style/format/feature_extractor.py
temporary `fix` for https://github.com/src-d/style-analyzer/issues/387
Feature extractor should be refactored after the release.
> Disable label filtering on analyze stage

- lookout/style/format/quality_report_noisy.py
- lookout/style/format/templates/noisy_quality_report.md.jinja2
This is an example of the current rendering
> Improve the noisy quality report rendering

- lookout/style/format/feature_extractor.py
Fixes https://github.com/src-d/style-analyzer/issues/399
> Fix class_sequences_to_labels and labels_to_class_sequences creation

- Makefile
it works fine and helps to avoid such bugs as here: https://github.com/bblfsh/bblfshd/issues/219
> Bump bblfshd version

- lookout/style/format/feature_extractor.py
- lookout/style/format/tests/test_postprocess.py
Fixes https://github.com/src-d/style-analyzer/issues/406
`_remove_labels_with_low_support` tried to use generator twice. So second time was absolutely useless and no actual filtering was applied.
> Make _remove_labels_with_low_support work

- lookout/style/format/analyzer.py
- lookout/style/typos/analyzer.py
> Fix string versions

- lookout/style/format/cmdline_tools.py
- lookout/style/format/tests/test_main.py
> Defer toolbox imports

- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/cmdline_tools.py
- lookout/style/format/descriptions.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/features.py
- lookout/style/format/langs/javascript/token_unwrappers.py
- lookout/style/format/postprocess.py
- lookout/style/format/quality_report.py
- lookout/style/format/quality_report_noisy.py
- lookout/style/format/rule_stat.py
- lookout/style/format/rules.py
- lookout/style/format/tests/code_generator_data.py
- lookout/style/format/tests/test_descriptions.py
- lookout/style/format/tests/test_model.py
- lookout/style/format/tests/test_quality_report.py
- lookout/style/format/tests/test_rule_stat.py
- lookout/style/format/tests/test_rules.py
- lookout/style/format/virtual_node.py
- lookout/style/format/visualizer/server.py
- lookout/style/typos/analyzer.py
- lookout/style/typos/corrector.py
- lookout/style/typos/generation.py
- lookout/style/typos/tests/test_corrector_utils.py
- lookout/style/typos/utils.py
- requirements-lint.txt
- setup.py
> Add trailing commas check

- lookout/style/format/benchmarks/top_repos_quality.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/quality_report.py
- lookout/style/format/rule_stat.py
- lookout/style/format/templates/model_report.md.jinja2
- lookout/style/format/templates/quality_report.md.jinja2
- lookout/style/format/tests/test_analyzer_integration.py
- lookout/style/format/tests/test_quality_report.py
- lookout/style/format/tests/test_rule_stat.py
- requirements.txt
Script to generate a report on several top repositories.
Related to https://github.com/src-d/style-analyzer/issues/311.
> Report quality on several top repositories

- lookout/style/format/benchmarks/evaluate_smoke.py
This was easy 
Fix https://github.com/src-d/style-analyzer/issues/368
> Fix condition for error check

- lookout/style/format/feature_extractor.py
- lookout/style/format/tests/code_generator_data.py
> Don't add noop after indentation

- lookout/style/format/tests/test_analyzer.py
- lookout/style/format/tests/test_code_generator.py
- lookout/style/format/tests/test_descriptions.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_quality_report.py
- lookout/style/format/tests/test_rules_integration.py
Closes https://github.com/src-d/style-analyzer/issues/432
> Specify special configs to run tests faster

- lookout/style/format/analyzer.py
> Turn on prune_attributes

- lookout/style/format/cmdline_tools.py
- lookout/style/format/quality_report_noisy.py
- lookout/style/format/tests/test_quality_report_noisy.py
Fixed https://github.com/src-d/style-analyzer/issues/450
> Fix the computation of the empirical confidence thresholds

- lookout/style/format/benchmarks/general_report.py
- lookout/style/format/templates/model_report.md.jinja2
> Include the model cofiguration into the template

- .travis.yml
- lookout/style/format/rules.py
- lookout/style/format/tests/test_postprocess.py
> Make `tests` directories read-only

- Makefile
- lookout/style/format/cmdline_tools.py
Closes https://github.com/src-d/style-analyzer/issues/313
> Add make release-report

- lookout/style/format/analyzer.py
- lookout/style/format/tests/test_quality_report.py
> Change the confidence threshold from 95 to 92

- lookout/style/format/analyzer.py
- lookout/style/format/rules.py
- lookout/style/format/tests/test_rules.py
- lookout/style/format/tests/test_rules_integration.py
closes: https://github.com/src-d/style-analyzer/issues/468
> Add confidence threshold pruning to the TrainableRules

- lookout/style/format/postprocess.py
- lookout/style/format/tests/test_postprocess.py
> Fix quote prediction & tests

- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/quality_report_noisy.py
- lookout/style/format/code_generator.py
- lookout/style/format/descriptions.py
- lookout/style/format/rules.py
- lookout/style/format/templates/comment.jinja2
- lookout/style/format/tests/test_code_generator.py
- lookout/style/format/tests/test_comment_generation.py
- lookout/style/format/tests/test_quality_report.py
- lookout/style/format/visualizer/server.py
- lookout/style/format/visualizer/src/Details.tsx
Fixes https://github.com/src-d/style-analyzer/issues/461.
So there are fixes for two bugs. 
1. If no rule is applicable we by default predict label 0 and rule 0.
2. We pick up the wrong rule to show because of two lists inconsistency: list with rule indexes and list with fixes.
> Fix Rules apply function and rule to show selection

- lookout/style/format/rules.py
Resolved here: https://github.com/src-d/style-analyzer/pull/478#discussion_r242475979
> Remove resolved comment

- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_quality_report.py
- lookout/style/format/virtual_node.py
> Fix empty string labeling

- lookout/style/format/analyzer.py
Fixes https://github.com/src-d/style-analyzer/issues/460
`group_line_nodes` was broken. With it fixed (and an additional fix of the test @vmarkovtsev used), the generated `FileFix` looks fine and the test of #490 passed.
@zurk, I removed the optimization of `vnodes` traversal because the logic was very obscure with the `continue` and `break` that interfered with the incrementation of `vnode_index`. You're more than welcome to add it back (since it wasn't critical but it was late I didn't spend time on it).
> Fix group_line_nodes

- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/general_report.py
- lookout/style/format/benchmarks/top_repos_quality.py
- lookout/style/format/templates/quality_report.md.jinja2
- lookout/style/format/tests/test_comment_generation.py
- lookout/style/format/tests/test_quality_report.py
Closes https://github.com/src-d/style-analyzer/issues/484
> Add PPCR metric calculation

- lookout/style/format/benchmarks/general_report.py
As found by @zurk iterators were used twice :man_facepalming: 
> Fix the quality report generation

- .travis.yml
- lookout/style/__init__.py
- setup.py
> Fix pypi deployment by tag

- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/cmdline_tools.py
- lookout/style/format/tests/test_evaluate_smoke.py
- requirements.txt
- setup.py
This PR is required: 
https://github.com/src-d/lookout-sdk-ml/pull/30
This PR contains:
- Fix for parameter names for config.
- Add bblfsh parameter handling.
> Fix arguments of evaluate smoke cmd command

- lookout/style/format/analyzer.py
We need to create the logger with the same domain as the factual class name,
otherwise, inheritors log ambiguously.
> Submit a few metrics and improve the logging

- lookout/style/format/benchmarks/top_repos_quality.py
> Add detailed progress banners to top report

- lookout/style/format/benchmarks/top_repos_quality.py
- lookout/style/format/templates/quality_report.md.jinja2
- lookout/style/format/tests/test_quality_report.py
* report for all samples
* handle empty report
* minor improvements to avoid hardcoding
> Fix report

- lookout/style/format/templates/quality_report.md.jinja2
> Minor fix in template - print full_support as integer

- lookout/style/format/benchmarks/top_repos_quality.py
Closes https://github.com/src-d/style-analyzer/issues/513
> Use bblfsh argument for top_repos_quality entry point

- lookout/style/format/feature_extractor.py
- lookout/style/format/tests/bugs/003_clasify_vnodes_negative_col/__init__.py
- lookout/style/format/tests/bugs/003_clasify_vnodes_negative_col/jquery.layout.js
- lookout/style/format/tests/bugs/003_clasify_vnodes_negative_col/test.py
- lookout/style/format/tests/test_features.py
New bug, discovered after https://github.com/src-d/style-analyzer/pull/519
> Add test for virtual nodes position in the end of file

- .travis.yml
- Dockerfile
- Makefile
- requirements.txt
> Ensure the correct version of lookout-sdk-ml in docker

- Makefile
- lookout/style/format/analyzer.py
- lookout/style/format/descriptions.py
- lookout/style/format/features.py
- lookout/style/format/optimizer.py
- lookout/style/format/templates/comment.jinja2
- lookout/style/format/tests/test_analyzer.py
- lookout/style/format/tests/test_comment_generation.py
- lookout/style/format/tests/test_descriptions.py
- setup.py
> Print rule hashes in the comments

- lookout/style/format/benchmarks/generate_smoke.py
- lookout/style/format/benchmarks/top_repos_quality.py
* handle custom modification functions as well as regexp 
https://github.com/src-d/style-analyzer/issues/526#issuecomment-454801024
* use dulwich in the future
https://github.com/src-d/style-analyzer/issues/526#issuecomment-454804489
* switch to numpy arrays
https://github.com/src-d/style-analyzer/issues/526#issuecomment-454808654
https://github.com/src-d/style-analyzer/issues/526#issuecomment-454809317
> Complete several TODOs

- lookout/style/format/analyzer.py
> Remove double feature selection

- lookout/style/format/benchmarks/top_repos_quality.py
> Replace vue-cli with revealjs

- lookout/style/format/analyzer.py
> Reduce the number of hyperopt iterations to 50

- lookout/style/format/model.py
- lookout/style/format/tests/test_model.py
> Print classification reports from the model

- lookout/style/format/analyzer.py
- lookout/style/format/descriptions.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/rules.py
- lookout/style/format/tests/test_descriptions.py
- lookout/style/format/utils.py
> Categorical pruning

- lookout/style/format/analyzer.py
> Change the size limit to 5MB

- lookout/style/format/analyzer.py
- lookout/style/format/utils.py
> Tweak logging

- .travis.yml
- Dockerfile
- lookout/style/format/analyzer.py
- lookout/style/format/tests/test_analyzer.py
- requirements.txt
- setup.py
> Train format analyzer on 20% different code

- lookout/style/format/rules.py
> Print attr pruning progress to logs if not a tty

- lookout/style/format/analyzer.py
> Fix 20% changes review suggestions

- lookout/style/format/analyzer.py
- lookout/style/format/rules.py
> Change cliques to community detection

- lookout/style/format/analyzer.py
- lookout/style/format/code_generator.py
- lookout/style/format/descriptions.py
- lookout/style/format/templates/comment.jinja2
- lookout/style/format/tests/test_analyzer.py
- lookout/style/format/tests/test_code_generator.py
Closes https://github.com/src-d/style-analyzer/issues/557.
A lot of small details to explain. I am going to review myself to do it.
New comments on the same examples from the issue:
1. https://github.com/zurk/redux/pull/4 
2. https://github.com/zurk/redux/pull/5 
3. https://github.com/zurk/redux/pull/6
> Fix style analyzer comment generation and suggestion feature

- Makefile
I use it a lot of times and it works as fine as 2.10.0
> Update bbflshd to 2.11.0

- Makefile
- lookout/style/format/benchmarks/quality_report_noisy.py
- lookout/style/format/cmdline_tools.py
- lookout/style/format/research/train.py
- lookout/style/format/tests/test_quality_report_noisy.py
Fix noisy report if included format model is outdated
> Add retrain flag to noisy report

- lookout/style/format/analyzer.py
- lookout/style/format/rules.py
> Improve the log messages in prod

- doc/how-to/demo.md
> Fix how-to demo

- lookout/style/format/analyzer.py
> Rename get_train_test_split -> split_train_test

- lookout/style/format/benchmarks/data/quality_report_repos_with_vnodes_number.csv
Related to https://github.com/src-d/style-analyzer/issues/608
Just a few numbers were changed.
>  Update quality_report_repos_with_vnodes_number.csv

- lookout/style/format/feature_extractor.py
I forget to update the last line of `_merge_classes_to_composite_labels` with the same logic.
> Fix for last line trailing space

- lookout/style/format/analyzer.py
Closes https://github.com/src-d/style-analyzer/issues/606
> Handle exceptions from CodeGenerator

- lookout/style/format/code_generator.py
On the trail of https://github.com/src-d/style-analyzer/pull/620#pullrequestreview-205104143
> Change CodeGenerator staticmethods to classmethods

- lookout/style/format/tests/test_analyzer_integration.py
Closes PR https://github.com/src-d/style-analyzer/pull/632
Fix part from https://github.com/src-d/style-analyzer/pull/632.
> Fix long running tests

- lookout/style/typos/analyzer.py
- lookout/style/typos/corrector.py
- lookout/style/typos/corrector_manager.py
- lookout/style/typos/generation.py
- lookout/style/typos/ranking.py
- lookout/style/typos/utils.py
- requirements.txt
- setup.py
Based on #625. Forth and final part of #615.
> Fix mistakes and style in docs

- lookout/style/__init__.py
> Bump the package version

- requirements.txt
- setup.py
I created a temporary fork. The feature is already merged so having a new official package is a question of time.
> Temporarily change smart_open to srcd_smart_open

- lookout/style/format/benchmarks/analyzer_context_manager.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/benchmarks/expected_vnodes_number.py
- lookout/style/format/benchmarks/general_report.py
- lookout/style/format/benchmarks/quality_report.py
- lookout/style/format/tests/test_analyzer_integration.py
- lookout/style/format/tests/test_evaluate_smoke.py
- lookout/style/format/tests/test_quality_report.py
Closes https://github.com/src-d/style-analyzer/issues/434
> Join TestAnalyser and AnalyzerContextManager

- lookout/style/format/benchmarks/general_report.py
- lookout/style/format/templates/model_report.md.jinja2
- lookout/style/format/tests/test_quality_report.py
Closes https://github.com/src-d/style-analyzer/issues/553
> Fix model report with respect to analyze config

- lookout/style/common.py
- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/benchmarks/general_report.py
- lookout/style/format/tests/test_descriptions.py
- lookout/style/format/tests/test_utils.py
- lookout/style/format/utils.py
It is a preparation for using this function in typos corrector.
> Move merge_dicts to common style utils

- lookout/style/common.py
- lookout/style/format/__init__.py
- lookout/style/format/benchmarks/general_report.py
- lookout/style/typos/corrector.py
- lookout/style/typos/metrics.py
- lookout/style/typos/templates/scores.md.jinja2
- lookout/style/typos/tests/test_metrics.py
- setup.py
Add metrics functions to typos and corrector evaluation function.
> Add metrics to typos

- README.md
Signed-off-by: Konstantin Slavnov <konstantin@sourced.tech>
> Change the Travis badge in the README from org to com

- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/benchmarks/general_report.py
- lookout/style/format/benchmarks/quality_report.py
- lookout/style/format/cmdline_tools.py
- lookout/style/format/config.py
- lookout/style/format/templates/model_report.md.jinja2
- lookout/style/format/tests/bugs/002_bad_line_positions/test.py
- lookout/style/format/tests/bugs/003_classify_vnodes_negative_col/test.py
- lookout/style/format/tests/bugs/004_generate_each_line/test.py
- lookout/style/format/tests/test_analyzer.py
- lookout/style/format/tests/test_code_generator.py
- lookout/style/format/tests/test_comment_generation.py
- lookout/style/format/tests/test_descriptions.py
- lookout/style/format/tests/test_evaluate_smoke.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_quality_report.py
- lookout/style/format/tests/test_rules_integration.py
- lookout/style/format/tests/test_uast_stability_checker.py
Closes https://github.com/src-d/lookout-sdk-ml/issues/17 on style analyzer side. 
I also move our 70 line config to the separate file. 
A lot of files changed, but everything is just about adopting the code to new config structure.
> Merge train and analyze configs

- lookout/style/format/benchmarks/evaluate_smoke.py
Closes https://github.com/src-d/style-analyzer/issues/651
> Remove repo_name from config in smoke evaluation

- lookout/style/typos/corruption.py
- lookout/style/typos/tests/test_corruption.py
Small refactoring of artificial typos' creation. Now it works hundreds of times faster.
> Speed-up typos creation

- lookout/style/typos/preparation.py
- lookout/style/typos/preprocessing.py
- lookout/style/typos/tests/test_corrector.py
- lookout/style/typos/tests/test_preparation.py
Small wrapper for generating trained TyposCorrector.
> Train corrector function

- lookout/style/format/benchmarks/quality_report_noisy.py
- lookout/style/format/cmdline_tools.py
- lookout/style/format/tests/test_analyzer.py
- lookout/style/format/tests/test_evaluate_smoke.py
- lookout/style/format/tests/test_quality_report_noisy.py
> Optimize style-analyzer tests 

- requirements.txt
- setup.py
We use functionality and format that is not supported in the older version.
> Fix gensim version

- lookout/style/typos/tests/test_corrector.py
- lookout/style/typos/tests/test_corrector_utils.py
- lookout/style/typos/tests/test_generation.py
- lookout/style/typos/tests/test_preparation.py
- lookout/style/typos/tests/test_ranking.py
Just add `keep_defaults_na = False` to all `pandas.read_csv()` and small fix of outdated test data format (lists instead of strings).
> Refactor tests

- lookout/style/typos/tests/test_corrector.py
- lookout/style/typos/tests/test_corrector_utils.py
- lookout/style/typos/tests/test_generation.py
- lookout/style/typos/tests/test_preparation.py
- lookout/style/typos/tests/test_ranking.py
- lookout/style/typos/utils.py
Refactor the function to remove support for outdated functionality.
Based on #677 - there tests are changed so that to correspond with this function.
> Refactor add_context_info()

- lookout/style/typos/templates/scores.md.jinja2
Just making template more pretty, sort rows
> Edit score report template

- lookout/style/typos/corrector.py
- lookout/style/typos/generation.py
- lookout/style/typos/tests/test_generation.py
- Add multiprocessing management features
- Small refactoring of parameters handling
- Fix problems with modelforge binding
> Refactor generator

- lookout/style/typos/corrector.py
- lookout/style/typos/generation.py
- lookout/style/typos/tests/test_generation.py
Add several new features to candidates generator.
Based on #681
> Add features to candidates generator

- lookout/style/typos/analyzer.py
- lookout/style/typos/tests/test_analyzer.py
> Add logic for reconstruction of identifier given predictions

- lookout/style/typos/corrector.py
- lookout/style/typos/corrector_manager.py
- lookout/style/typos/corruption.py
- lookout/style/typos/generation.py
- lookout/style/typos/preparation.py
- lookout/style/typos/tests/test_corrector.py
- lookout/style/typos/tests/test_corruption.py
- lookout/style/typos/tests/test_generation.py
- lookout/style/typos/tests/test_preparation.py
Train from scratch function, just wraps up all preparation functions.
I am not shure of the best way to handle parameters here. All the preparation functions will also have wrappings for CL usage. So I prefer passing dictionaries to specifying all the defaults in several places, but I'm not shure it's a good practice.
Will be glad to any advice on the subject.
> Add train from scratch function

- Makefile
Closes https://github.com/src-d/style-analyzer/issues/675
> xz report log files

- lookout/style/typos/__init__.py
- lookout/style/typos/__main__.py
- lookout/style/typos/cmdline_tools.py
- lookout/style/typos/preparation.py
- lookout/style/typos/tests/test_preparation.py
Ready to take suggestions for improving parameters handling.
Based on #684.
> Add command line interface for all preparation functions.

- lookout/style/format/benchmarks/quality_report.py
Small PR that polishes changes in https://github.com/src-d/style-analyzer/pull/665 and fix report filenames to correspond with report `v0.1.0`.
> Fix quality report generation

- lookout/style/typos/analyzer.py
- lookout/style/typos/cmdline_tools.py
- lookout/style/typos/corrector.py
- lookout/style/typos/corruption.py
- lookout/style/typos/metrics.py
- lookout/style/typos/preparation.py
Nothing important and code behavior is the same.
> Minor code and documentation improvements for typos

- lookout/style/typos/preparation.py
This changes are important and without them I was not able to run train_from_scratch()
> Fix train_from_scratch()

- lookout/style/typos/corrector.py
- lookout/style/typos/corruption.py
- lookout/style/typos/preparation.py
- lookout/style/typos/ranking.py
Logging should be improved in a lot of places related to typos.
I add just a basic logging needed to understand what is going on while running ` train_from_scratch()`
> Add minimum logging to run train_from_scratch()

- lookout/style/typos/analyzer.py
- lookout/style/typos/corrector_manager.py
* fix IdTyposAnalyzer
* update `typos/__init__.py` - now `lookout list` shows IdTyposAnalyzer
* updates `corrector_manager.py`
Related [issue](https://github.com/src-d/style-analyzer/issues/686)
Depends on https://github.com/src-d/style-analyzer/pull/673 (& intersects with https://github.com/src-d/style-analyzer/pull/688/files)
> Reanimate typos

- lookout/style/typos/analyzer.py
- lookout/style/typos/tests/test_analyzer.py
handle config default values the same way we do in style analyzer.
It is always a good idea to have process identical things the same way.
> Sync config handling in typos and style analyzers

- lookout/style/typos/analyzer.py
- lookout/style/typos/utils.py
It is the first PR in the next series of PRs that is needed to have a quality report system.
It changes Typos Analyzer to be similar to Format Analyzer.
I extracted one main functions with all logic inside: `generate_typos_fixes` that almost all I need to be able to create a report system.
> Prepare Typos Analyzer to be evaluated

- lookout/style/format/config.py
> Simplify comment_template construction

- lookout/style/typos/analyzer.py
- lookout/style/typos/modelforgecfg.py
> Load corrector from the modelforge

- lookout/style/typos/analyzer.py
- lookout/style/typos/corrector.py
- lookout/style/typos/corruption.py
- lookout/style/typos/ranking.py
- lookout/style/typos/tests/test_corrector_utils.py
- lookout/style/typos/utils.py
Replace `Tuple[str, float]` with `Candidate` added by @zurk.
> Use Candidate class in corrector suggestions logic

- lookout/style/typos/corrector_manager.py
> Fix `TyposCorrector` creation

- Dockerfile
- Makefile
- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/evaluate_smoke.py
- lookout/style/format/benchmarks/expected_vnodes_number.py
- lookout/style/format/benchmarks/general_report.py
- lookout/style/format/benchmarks/quality_report_noisy.py
- lookout/style/format/feature_extractor.py
- lookout/style/format/langs/javascript/uast_fixers.py
- lookout/style/format/tests/bugs/002_bad_line_positions/test.py
- lookout/style/format/tests/bugs/004_generate_each_line/test.py
- lookout/style/format/tests/test_analyzer.py
- lookout/style/format/tests/test_code_generator.py
- lookout/style/format/tests/test_comment_generation.py
- lookout/style/format/tests/test_descriptions.py
- lookout/style/format/tests/test_expected_vnodes_number.py
- lookout/style/format/tests/test_features.py
- lookout/style/format/tests/test_quality_report.py
- lookout/style/format/tests/test_rules_integration.py
- lookout/style/format/tests/test_uast_stability_checker.py
- lookout/style/format/uast_stability_checker.py
- lookout/style/format/virtual_node.py
- lookout/style/typos/analyzer.py
- requirements.txt
- setup.py
Closes https://github.com/src-d/style-analyzer/issues/666
It is a draft PR.
Plan:
Wait for driver v2.7.0 release, test it and finish PR.
> Use javascript-driver v2.7.0

- lookout/style/typos/tests/test_corrector_utils.py
- lookout/style/typos/utils.py
Migration to `Candidate` class was missed in one place, fixed it.
> Fix return all

- .travis.yml
- Dockerfile
- lookout/style/format/analyzer.py
- lookout/style/format/benchmarks/general_report.py
- lookout/style/format/cmdline_tools.py
- lookout/style/format/langs/javascript/__init__.py
- lookout/style/format/tests/test_quality_report.py
- requirements.txt
- setup.py
This feature requires an update of `lookout-sdk-ml`
> Check the language driver version

- lookout/style/typos/corrector.py
Supersmall change that makes model testing more user-friendly (i need it for training-testing myself).
> Return suggestions and report in TyposCorrector.evaluate()

- lookout/style/format/uast_stability_checker.py
> Fix UASTFixer reliance on non-existing invariant of parent covers children

- lookout/style/typos/research/eval_dataset/get_correct_dataset_entries.py
Script I use to get dataset in https://github.com/src-d/style-analyzer/pull/737
> Add get_correct_dataset_entries.py to research

- lookout/style/__init__.py
@m09 last deployment failed because I forget to bump the version:
https://api.travis-ci.com/v3/job/192903374/log.txt
Is it possible to recreate the tag after we merge the PR?
> Bump the version

- lookout/style/typos/tests/test_corrector_utils.py
> Add allow_pickle arg to numpy.load()

- Dockerfile
- lookout/style/typos/research/eval_dataset/filter_commits.py
- lookout/style/typos/research/eval_dataset/filter_commits_post.py
- lookout/style/typos/research/eval_dataset/mine.ipython
- requirements.txt
- setup.py
One month of running 4 machines, 12 cores each - for nothing :cry:
> Fix typos dataset generation error: case sensitivity

- Makefile
- lookout/style/format/research/min-samples-leaf.py
- lookout/style/format/research/size.py
- lookout/style/typos/research/eval_dataset/filter_commits.py
- lookout/style/typos/research/eval_dataset/filter_commits_post.py
- lookout/style/typos/research/eval_dataset/filter_dataset.py
- lookout/style/typos/research/eval_dataset/prepare_dataset.py
- lookout/style/typos/research/pick_subset.py
Closes https://github.com/src-d/style-analyzer/issues/768
Also I add a simple check `pycodestyle --max-line-length=99` for research directories
> Fix style in research directories

- MAINTAINERS
- maintainers.md
As required in https://github.com/src-d/guide/issues/315
I stop Travis CI check because I clog the Travis queue otherwise.
> Fix MAINTAINERS file

- lookout/style/typos/analyzer.py
Once the https://github.com/src-d/models/pull/24 is merged, the model should be updated in style-analyzer by merging this PR.
> Change default modelforge TyposCorrector model id

- .travis.yml
Signed-off-by: Maartje Eyskens <maartje@eyskens.me>
> Deploy the Helm chart from the new stable charts repo

- lookout/style/typos/config.py
- lookout/style/typos/ranking.py
- Change xgb parameters
- Allow for xgb training verbosity management from the total corrector config
- Hard-split training and validation samples for xgb training by the checked tokens
> Refactor ranking in typos
